### ISSUE TITLE
inability to omit `mdast-` for plugins in .mdastrc

### ISSUE THREAD

**Issue by iamstarkov** [wooorm/mdast#100]
> When a plugin is prefixed with mdast- (which is recommended), the prefix can be omitted in the plugin list or map.
> — [mdast.5 doc](https://github.com/wooorm/mdast/blob/master/doc/mdastrc.5.md#plugins)

but apparently it doesnt work, found it while was reporting #99

**Comment by wooorm** [comment]
This should work, but there’s some handling for globally installed plug-ins / mdast necessary.

Could you provide me with information where `mdast` and `mdast-textr` are located?

**Comment by wooorm** [comment]
@iamstarkov Ping!

**Comment by iamstarkov** [comment]
they are [located locally](https://github.com/denysdovhan/pl/blob/master/package.json#L7-L8)
just run these lines:
```
git clone git@github.com:denysdovhan/pl.git
cd pl
npm install

cat .mdastrc
npm test # fine, because mdast-textr hadnt been found

git checkout mdast/no-problem
cat .mdastrc
npm test # bunch of problems, because of #99, but mdast-textr had been found and used
```

**Comment by wooorm** [comment]
With the recent fix (4bb02b2) I get the following error:

```
foo.md
        1:1  error    TypeError: mws[i].apply is not a function
    at exec (/Users/tilde/projects/oss/pl/node_modules/textr/index.js:77:21)
    at api (/Users/tilde/projects/oss/pl/node_modules/textr/index.js:49:17)
    at /Users/tilde/projects/oss/pl/node_modules/mdast-textr/index.es5.js:35:11
    at one (/Users/tilde/projects/oss/pl/node_modules/unist-util-visit/index.js:96:22)
    at /Users/tilde/projects/oss/pl/node_modules/unist-util-visit/index.js:83:29
    at forwards (/Users/tilde/projects/oss/pl/node_modules/unist-util-visit/index.js:24:13)
    at all (/Users/tilde/projects/oss/pl/node_modules/unist-util-visit/index.js:82:16)
    at one (/Users/tilde/projects/oss/pl/node_modules/unist-util-visit/index.js:100:20)
    at /Users/tilde/projects/oss/pl/node_modules/unist-util-visit/index.js:83:29
    at forwards (/Users/tilde/projects/oss/pl/node_modules/unist-util-visit/index.js:24:13)
```

That seems to have to do with how `mdast-textr` passes middleware to `textr`, not with mdast.

Can I assume that 4bb02b2 closed this too?

**Comment by iamstarkov** [comment]
do you get this error in pl’s master branch?

**Comment by wooorm** [comment]
No, I got it on `mdast/no-problem`.

But, the master branch doesn’t seem to pass any plug-ins, even with the aforementioned mdast fix.

**Comment by iamstarkov** [comment]
yep, with there are no problems with `no-problems` branch, because there mdast-textr added to to `.mdastrc` without ommitting `mdast-`.

> But, the master branch doesn’t seem to pass any plug-ins, even with the aforementioned mdast fix.

yep, the problem is with master where `mdast-` omitted https://github.com/denysdovhan/pl/pull/2/files. So mdast-textr is not even required by mdast-cli. #101 doesnt relate to this issue

**Comment by wooorm** [comment]
Thanks. There’s still some stuff wrong with textr/mdast-textr but I’ll leave that up to you :)

**Comment by iamstarkov** [comment]
thank you for fix. and we will fix mdast-textr today =)

**Comment by wooorm** [comment]
:+1:
