### ISSUE TITLE
Incorrectly eaten value

### ISSUE THREAD

**Issue by ondine** [wooorm/mdast#102]
![incorrectlyeatenvalue](https://cloud.githubusercontent.com/assets/3281541/11597656/cfa64010-9a71-11e5-8726-5dff23df60bd.png)

**Comment by wooorm** [comment]
Is this related to tables, and related to linter-markdown in particular? See GH-97.

**Comment by wooorm** [comment]
@ondine, could you check this?

**Comment by ondine** [comment]
Hi Tutus,

Sure, I can check tomorrow, sorry I don't check this email account that
often.

Best,

Ondine

**Comment by Arcanemagus** [comment]
@ondine linter-markdown v1.2.2 has been released that updated mdast, please file an issue over there if you have any issues.

**Comment by wooorm** [comment]
Thanks @Arcanemagus!

This should be fixed, but if not, please raise another issue / comment here!

**Comment by ondine** [comment]
Hi Titus,

I looked into it, but couldn't find in my screenshot a reference to which
document I was working on at the time that error came up. My apologies. But
yes, i think it was due to the issue GH-97 you mentioned.

I'm attaching one last screenshot from Monday, but I need to check my
linter markdown version...will do so now. Okay, so I'm on 1.2.1 and just
upgraded to 1.2. 3.

Thanks!

Ondine

**Comment by wooorm** [comment]
:+1:

**Comment by ColinAnthony** [comment]
Got this error:
`1:1: Incorrectly eaten value`

when trying to access this link from the admin page to delete it.
https://colinator-prints.netlify.com/admin/#/collections/post/entries/basic-rules-for-walking-in-the-mountains

**Comment by wooorm** [comment]
@ColinAnthony This is probably an issue with the plugins you’re using. There have been similar issues [over the years](https://github.com/remarkjs/remark/search?q=Incorrectly+eaten+value&type=Issues), most recently https://github.com/remarkjs/remark/issues/443. That’s probably it.

**Comment by ColinAnthony** [comment]
@wooorm Thanks,
I guess it might be the Netlify, since my build is:
Fjord-theme + Hugo + Netlify CMS + GitHub/Netlify
and [this](https://github.com/remarkjs/remark/issues/409) is basically my issue.
I'll look into that side of things!
