### ISSUE TITLE
non-loose list items should not have a paragraph child

### ISSUE THREAD

**Issue by yaycmyk** [wooorm/mdast#104]
using `mdast.parse()`:

```js
mdast.parse("- xyz\n- abc\n- foo");
```

Yields a `list` AST node, with three `listItem` children that contain `paragraph` nodes.

Based on the [Markdown spec for lists](https://daringfireball.net/projects/markdown/syntax#list), there should be no paragraph node wrapping the text of the list item if there is no extra padding newline directly after the list item.

```js
mdast.parse("- xyz\n\n- abc\n\n- foo");
```

Should emit a structure with the paragraphs inside.

**Comment by wooorm** [comment]
Note that the markdown spec contains two parts: reading markdown, and compiling HTML. I read that sentence as being related to HTML.

Whether a paragraph is rendered depends on the output mechanism. In HTML and JSX, there shouldn’t be such a node of course, but other syntaxes might need it (e.g., man pages).

By always keeping block-level nodes inside list-items (e.g., a paragraph or a block-quote) instead of sometimes exposing inline-level nodes (e.g., links and emphasis) makes processing the syntax tree a lot easier.

I opt for keeping the paragraph inside list-items in all cases.

P.S. See how I implemented the logic in [mdast-html »](https://github.com/wooorm/mdast-html/blob/4315c6e95cf64027890ea4da79ec71ab76071eca/lib/compilers.js#L435-L437).

**Comment by yaycmyk** [comment]
@wooorm Actually it does matter, the specific excerpt:

> If list items are separated by blank lines, Markdown will wrap the items in <p> tags in the HTML output. For example, this input:
>
>```markdown
>*   Bird
>*   Magic
>```
>will turn into:
> ```html
> <ul>
> <li>Bird</li>
> <li>Magic</li>
> </ul>
> ```
> But this:
>```markdown
> *   Bird
>
> *   Magic
>```
> will turn into:
> ```html
> <ul>
> <li><p>Bird</p></li>
> <li><p>Magic</p></li>
> </ul>
> ```

In https://daringfireball.net/projects/markdown/syntax#list

**Comment by wooorm** [comment]
Thanks for your reply, @yaycmyk.

I still don’t agree. The input/output you posted can’t be compared to mdast, it can only compared to mdast and mdast-html or mdast and mdast-react, which both get this right.

Again, the most important reason for this is that the spec of the original markdown makes stuff very hard for plug-ins. Most importantly, it’s not just either-or, there’s also a huge difference between “pedantic” markdown / GFM markdown / commonmark markdown regarding to paragraphs, making things even harder.

Most importantly, what a paragraph means in mdast can be different from what a `<p>` node means in HTML.

I understand your question, but I don’t agree on your conclusion (“It's definitely up to the parser to only add paragraph AST nodes when specifically needed.”). In my opinion, it’s the job of the compiler to handle conversion from a syntax tree to HTML, which in your case is your custom JSX compiler. That compiler is supposed to do this.

**Comment by yaycmyk** [comment]
> Most importantly, what a paragraph means in mdast can be different from what a <p> node means in HTML.

How so? If that were true, you'd just emit the contents as a TextNode and be done with it. Paragraph means something very specific.

**Comment by yaycmyk** [comment]
And as a compiler, it doesn't make sense to have to do lookaheads through the tree so often to figure out if we have to unwrap children, with little information about the original structure of the markdown.

For example with the newline issue to wrap with `<p>`, if I look at the AST returned by `mdast.parse()`, I have no idea if the original markdown had extra newlines and that wrapping `<p>` was intentional. I understand there are some differences between the different markdown variants, but this is kind of important and can materially change how the content should be emitted.

**Comment by wooorm** [comment]
I think the most important concept for me is that there’s a difference between the syntax tree format, and the compiler. You constantly omit the use of plug-ins in your use-cases whereas they are the core of mdast. My goals with mdast are aligned differently from yours.

Also, you slightly hyperbolic in the case regarding “lookaheads through the tree so often”. Please check the example I linked mentioned above again.

An last but not least, mdast is an abstract syntax tree, not a concrete syntax tree. Not everything is stored, making the tree smaller and more easily manipulated, but loosing \*some\* information.
