### ISSUE TITLE
Nested tasklist

### ISSUE THREAD

**Issue by mizchi** [wooorm/mdast#17]
Here is trivial difference.

```
- [ ] aaa
  - [x] bbb
  - [ ] ccc
```

- [ ] aaa
  - [x] bbb
  - [ ] ccc

It looks mdast doesn't handle nested tasklist.

**Comment by wooorm** [comment]
what's the difference? Other than one is HTML while the other is markdown?
Indentation?

**Comment by mizchi** [comment]
Oops, it was resolved at v0.12. Sorry to forget checking before report

**Comment by wooorm** [comment]
Haha okay!
