### ISSUE TITLE
Can't parse html tag correctly

### ISSUE THREAD

**Issue by mizchi** [wooorm/mdast#18]
- can parse `<div>div</div>`  and `<pre>pre</pre>`
- `<a>foo</a>` and `<span>foo</span>`  

It looks inline tag can't be parsed.

```
coffee> mdast.parse('<a>foo</a>').children[0]
{ type: 'paragraph',
  children: 
   [ { type: 'html',
       value: '<a>',
       position: [Object] },
     { type: 'text',
       value: 'foo',
       position: [Object] },
     { type: 'html',
       value: '</a>',
       position: [Object] } ],
  position: 
   { start: { line: 1, column: 1 },
     end: { line: 1, column: 11 } } }
```

![](http://i.gyazo.com/9e6ab94abd93596df9f0677f92b5271c.png)

**Comment by wooorm** [comment]
It’s a feature, from the time this was [marked](https://github.com/chjj/marked).
It allows for markdown inside HTML: so `hello <sup>*world*</sup>!` will still work

In fact, [commonmark](http://spec.commonmark.org/dingus/?text=%3Cpre%3Epre%3C%2Fpre%3E%0A%0A---%0A%0A%3Cdiv%3Ediv%3C%2Fdiv%3E%0A%0A---%0A%0A%3Ca%3Efoo%3C%2Fa%3E%0A%0A---%0A%0A%3Cspan%3Eaaaaaaaa%3C%2Fspan%3E%0A%0A---%0A%0A%3Cbr%20%2F%3E%0A%0A---%0A%0Araw%0A) does a similar thing (check out the AST tab).

What arroyo trying to accomplish?

**Comment by mizchi** [comment]
I understood what it is.
Then I want to know where open tag and close tag, but it is my own task, not mdast.

Thank you your teaching!

**Comment by wooorm** [comment]
Cool! No problem :)
