### ISSUE TITLE
Cannot distinguish `|---|` and `|:---|`

### ISSUE THREAD

**Issue by uasi** [wooorm/mdast#19]
mdast parses un-aligned table column (`|---|`) as left-aligned, as well as `|:---|`. This makes it impossible to emulate GitHub's Markdown renderer -- it renders the header of un-aligned table column _center_, and the body _left_, by leaving their `text-align` style unspecified:

```markdown
|un-aligned(center)|center|left|
|---|:---:|:---|
|Lorem ipsum dolor sit amet|Lorem ipsum dolor sit amet|Lorem ipsum dolor sit amet|
|un-aligned(left)|center|left|
```

↓

|un-aligned(center)|center|left|
|---|:---:|:---|
|Lorem ipsum dolor sit amet|Lorem ipsum dolor sit amet|Lorem ipsum dolor sit amet|
|un-aligned(left)|center|left|

**Comment by wooorm** [comment]
Great catch! I was wondering if the singular treatment for both non-aligned and left-aligned would cause bugs somewhere and it looks like it finally did!

Thanks for pointing it out. I think this has to do with **markdown-table**. I’ll look tonight!

**Comment by wooorm** [comment]
There! That should work :smile:

**Comment by uasi** [comment]
Thanks! Now it works as I wanted!
