### ISSUE TITLE
range/location support?

### ISSUE THREAD

**Issue by azu** [wooorm/mdast#2]
Hi!

I notice that [CommonMark](https://github.com/jgm/CommonMark "CommonMark")'s AST has been implemented location info(but it is unstable).

```
{ t: 'Document',
  start_line: 1,
  start_column: 1,
  end_line: 20,
  children: []
}
```

An example is [azu/commonmark-ast-sandbox](https://github.com/azu/commonmark-ast-sandbox "azu/commonmark-ast-sandbox").

Do you have any plans to support `range` or `location` on AST(like [Esprima](http://esprima.org/doc/index.html "Esprima Documentation"))?

**Comment by sbruchmann** [comment]
/subscribe

Yes, this would be an awesome feature to have.

**Comment by wooorm** [comment]
I've began work, but found that the initial setup (from marked), and the whitespace-sentsitive language, pose problems. It probably requires more work than expected.

**Comment by azu** [comment]
Great work :bangbang: 
I'll try it.
