### ISSUE TITLE
Want a "don't merge HTML nodes" option

### ISSUE THREAD

**Issue by uasi** [wooorm/mdast#20]
Sometimes merged HTML nodes get in my way when transforming AST into vertual DOM.

We can't just split a seemingly-merged HTML node by `/\n\n/` because doing so breaks `<div>text\n\n</div>`[1] in `<div>text` and `</div>`. Though I'm fine with nodes whose value is simple tag (`<div>`, `</div>`) or balanced fragment (`<div>text</div>`), something like `<div>text` is not very acceptable.

[1] it can be obtained by parsing this Markdown document: 

```markdown
<div>text

</div>
```

**Comment by uasi** [comment]
Well, just noticed it is able to tell whether a node containing `\n\n` is merged by testing `node.position.start.line == node.position.end.line`...

**Comment by wooorm** [comment]
Which version of mdast are you using?

As in, with the above markdown example i get the following AST (on the latest mdast version):

```json
{
  "type": "root",
  "children": [
    {
      "type": "html",
      "value": "<div>text\n\n</div>",
      "position": {
        "start": {
          "line": 2,
          "column": 1
        },
        "end": {
          "line": 4,
          "column": 7
        }
      }
    }
  ],
  "position": {
    "start": {
      "line": 1,
      "column": 1
    },
    "end": {
      "line": 4,
      "column": 7
    }
  }
}
```

Regarding merging being an error. Why? Why is it an error to treat that document as a single HTML node, to ignore “balance”?

In addition, **mdast** is not an HTML parser. It doesn’t care about “valid” HTML—that’s one of the reason it’s so awesome: the strongness is detected in the following:

```markdown
<sup>**text**

</sup>
```

**Comment by wooorm** [comment]
Could you let me know if this referenced commit changes thing, and if not, could you desire more thoroughly what you want?

**Comment by wooorm** [comment]
Hey @uasi, I’m closing this due to no response. Let me know if this decision was made in error.
