### ISSUE TITLE
1.0.0?

### ISSUE THREAD

**Issue by anko** [wooorm/mdast#21]
*mdast* is currently on a [semver][1] "unstable" 0.x.x version. Is that intentional?

It seems to have [tests][2] with [full coverage][3], no open issues, no recent API breaks (though I haven't checked very carefully), and [a little bunch of dependent packages][4].

What's blocking a stable release?

[1]: http://semver.org/
[2]: https://github.com/wooorm/mdast/tree/master/test
[3]: https://coveralls.io/r/wooorm/mdast?branch=master
[4]: https://www.npmjs.com/browse/depended/mdast

**Comment by wooorm** [comment]
Interesting point. mdast is certainly internationally unstable. I’ve been wanting to reach 1.0.0 for some time now but IMHO, there are quite some breaking changes in recent commits and some more will come in the future.

I’m currently working on two plug-ins, behind the scenes: mdast-lint, which validates markdown, and mdast-html, which compiles to HTML.

Both plug-ins result in quite some changes in mdast itself, and i’d rather publish those first before reaching stable: I think those two packages are a good baseline for what tooling wants to know about markdown, to see if mdast exposes enough information, or too few (lately, rather the latter).

**Comment by wooorm** [comment]
Most concretely, I think if mdast would be on the stable track right now, I’ll have to release new major versions probably every week.

However, I do acknowledge that when you’re depended on IRL, you *should* be on a stable track. I’d really like to get their fast, but it seems like there’s still so much to do, to figure out, before I can safely say mdast really does what it promises.

I’m really happy with tool-authors for their interest and support, but I just can't promise stability right now.

Hope that clears things up?

**Comment by anko** [comment]
Sounds like a good plan. Do put up issues or a roadmap if you could use help.

Thanks for your great work and impeccable standards of quality! :star:

**Comment by wooorm** [comment]
Great to hear you dig the standards: I really do try to pay lots of attention to docs and quality, and it’s motivating to hear it’s appreciated.

I’ll try to formalise a roadmap here through GH issues soon, thanks for the suggestion!
