### ISSUE TITLE
Add list-item-indent stringification option

### ISSUE THREAD

**Issue by wooorm** [wooorm/mdast#31]
...which defaults to `"tab-size"`, for greatest support, but also accepts [`"mixed"`](http://www.cirosantilli.com/markdown-style-guide/#option-list-space-mixed) and [`"1"`](http://www.cirosantilli.com/markdown-style-guide/#option-list-space-1).

Supersedes GH-30.

**Comment by wooorm** [comment]
@hotoo This should do what you want. just pass `{listItemIndent: "1"}` to `mdast.stringify()`/`mdast.process()`!

**Comment by hotoo** [comment]
Good for me. :+1:
