### ISSUE TITLE
Lifecycle events for plugins

### ISSUE THREAD

**Issue by chrisdickinson** [wooorm/mdast#36]
Hey! Great work on mdast, it's really rad. I'm using it to set up a build system for the [Node.js documentation WG](https://github.com/nodejs/docs). As part of that effort, I started building [count-docula](https://github.com/chrisdickinson/count-docula), which currently consumes `mdast` and presents its own CLI. If possible, I'd love to make count-docula just another plugin that mdast consumes.

What count-docula is currently doing:

* Given a directory, it collects every markdown file within that directory.
  * This duplicates work from mdast's CLI.
* For each markdown file, the plugin looks for three directives (`import`, `export`, and `anchor`.)
  * Anchors are user-defined ids that are assigned to the closet parent block element — they're there so that heading text can be changed independent of links, and so that links can be tracked and verified across documents.
  * Once all anchors are found, then all exports are determined. These are links that will be made available when "importing" the current document.
  * Finally, the import directives are hit.
    * Importantly, import directives are able to bring in documents from *outside* the original working set.
* The plugin artificially blocks `process` from completing (using a function passed as an option) until all documents have been visited, and their anchors, exports, and imports declared.
  * Warnings are added at this stage for unknown|duplicate reference link definitions, bad imports, and bad exports.
* Once all documents have been visited & resolved, the plugin continues to the "render" or "test" task.
  * The `test` task augments `lint` with a test checking to see that no documents in the original working set are "orphaned" — only one document in the original working set may have no incoming links.
    * Otherwise, this step replicates much of `mdast`'s CLI machinery.
  * The `build` task accepts a template for rendering the document into, but otherwise works the same as `mdast`'s CLI machinery.

In order to turn count-docula into a plugin:

* `mdast`'s plugin API would need a lifecycle event for "the CLI has collected all of the docs in this dir." That event may be asynchronous, so `mdast` should delegate to the plugin before continuing (via a callback or other method.)
* The directory set API *may* have to be capable of adding new source `md` document paths and making the resulting ASTs available to the plugin.

Something like:

```javascript
module.exports = attacher(md, opts) {
  md.onDocsCollected((workingSet, next) => {
    // workingSet is an "array-ish" set of all of the `File` objects that
    // mdast's cli found.
    workingSet.parseEach(({filename, ast}, next) => {
      // search for documents to import from the AST
      workingSet.add('some/new/path')
      next()
    }, function(err) {
      workingSet.forEach(({filename, ast}) => {
        // resolve all of the links, then let `mdast` know that
        // the workingSet's files are ready to be rendered / tested / etc.
        // if the workingSet's files were parsed, use those asts
        // instead of parsing again. Otherwise parse them.
        next()
      })
    })
  })
}
```

Of course, there's *zero* pressure to do this — or if you'd like I would be happy to take a stab at implementing it. A `workingSet` API seems like a natural place to add meta information for other plugins, as well — for example, providing a template/framing API for mdast-html.

Thanks again, and great work on mdast!

**Comment by wooorm** [comment]
Thanks for the kind words @chrisdickinson! Additionally, the work you did on count-doula is really cool, and thanks for writing all this down.

One difficulty is that mdast plug-ins are loaded based on each file, that’s due to configuration files which could be in every directory, specifying new plug-ins and what-not.

However, your thinking on “blocking” `done` is really interesting. I’m thinking your feature request might just be possible by “queueing” until every file is found (there’s currently no way to find to when this is though). Then, as all files have a `filePath`, they could be grouped by directory.

There’s still something missing though: adding new file-paths (just like extensions, which I mentioned in GH-25).

I’ll try to play with this soon, hopefully today/tomorrow!

**Comment by wooorm** [comment]
Hmm, I’m bumping into some difficulties with plug-ins being attached based on each file. E.g., when someone `use`s a plug-in which receives a working-set, they could do that for one or more subdirectories, but not others. Not sure yet how to handle that.

**Comment by wooorm** [comment]
Been three hard-days, but I think the just-published version of **mdast**
does exactly what your wanting (`npm i mdast@next`).

I suggest first reading the commit message (ee5e603), for some insights, but
basically:

A new `fileSet` is passed to `attacher`: `attacher(mdast, options?, fileSet?)`.
Note that `attacher` is called multiple times (currently for every found file)
with the same file-set.

The two key things, relating to your last two points:

*   `FileSet` also has a method (`FileSet#add(File)`) which accepts
    a file object and runs all steps (the “file-pipeline”) on that file.

    Probably most notable, you should make sure they have a valid file-path
    relative to the CWD from where mdast(1) is run.

*   This `fileSet` has a `use` method, which accepts a `completer`. When the
    file-set has transformed all files (`done(err?)` is called by all
    transformers), the file-set’s middleware runs and `completer` is invoked
    with `fileSet` (and an optional `done(err?)` for asyncness).

    > Note that for ten files, `attacher` is invoked ten times, and
    > when attacher attaches a `completer`, that also happends ten times.
    > If you add a `pluginId` to the completer, the completer is only
    > added once!

    FileSet’s contain a list of files (`fileSet.valueOf()`), which each have a patched `ast` property housing the parsed AST.

IMHO this should enable you to transform **count-docula** into an **mdast** plugin!

Note that there’s not much documentation yet for `FileSet`, but reading [lib/cli/file-set](lib/cli/file-set), [lib/cli/file-set-pipeline/index.js](lib/cli/file-set-pipeline/index.js), and [lib/cli/file-pipeline/index.js](lib/cli/file-pipeline/index.js).

However, this does not extend mdast to support templating. I haven’t yet considered how that would work (probably by a completer?), and look forward to see how you’d do that. :+1:

**Comment by wooorm** [comment]
Alright, this just landed in `mdast@latest`. I added docs for file-sets in b33b724907649c3cb6d77613efc5c7dd6981d7bc, and created a similar tool (based on wooorm/mdast-lint#17) which checks a project for dead links (to headings and files). This project, [mdast-validate-links](https://github.com/wooorm/mdast-validate-links), first gathers all references to deep links and imports the linked files.

Later, when all files are transformed, it finds the exports for each file, and then it walks over all references to see if they point to such exports, and warns if this is not the case.

...so I consider this closed, but feel free to re-open this if you disagree.

Also: let me know how things go, or if I can help in any way!
