### ISSUE TITLE
Inverse order of attachers when passed in array

### ISSUE THREAD

**Issue by eush77** [wooorm/mdast#37]
Looking at [index.js](https://github.com/wooorm/mdast/blob/f693521ddb42e2ae581cdf6825bbc7058e51b017/index.js#L158-160), it seems that

```
mdast.use([plugin1, plugin2, plugin3])
```

is equivalent to

```
mdast.use(plugin3).use(plugin2).use(plugin1)
```

which is counter-intuitive if you ask me.

Why is it so?

**Comment by wooorm** [comment]
No idea why that’s so. Weird... Will work on that soon...
