### ISSUE TITLE
Github-flavored markdown html incompatibility

### ISSUE THREAD

**Issue by pjeby** [wooorm/mdast#40]
FYI, mdast does not parse HTML the way Github itself does.  More specifically, it doesn't parse *invalid* HTML the same way Github does, or at least invalid HTML comments.  If you have an HTML comment containing `--`, Github ignores this invalidity and still treats the overall comment as HTML and doesn't turn it into a paragraph.

I would say this is a bug rather than a feature, since no user-facing tool I've tried (e.g. Marked 2, MarkdownPad, MacDown, etc.) ever insists on HTML being *valid* HTML and reverting it to a paragraph otherwise.  Likewise, of the parsers I've tried, mdast seems to be unique in this respect.

**Comment by pjeby** [comment]
(Btw, I'm not letting this stop me from *using* mdast, since the html parsing rule is of course replaceable from my code, and I already have a regexp that works (`"<!--(?:[^-]|-(?!->))*-->"`).  I just thought you might not be aware of the issue.)

**Comment by wooorm** [comment]
Hmm Thanks for mentioning. This happened in 09ec06c4b2f94c05f73bc33b1281d64db8e1dc8d when I added CommonMark support, but it seems to regress on normal GFM support. I’ll look into it, and please do let me know if you find more! 😉
