### ISSUE TITLE
uglify breaks mdast

### ISSUE THREAD

**Issue by tmcw** [wooorm/mdast#41]
I've just created a testcase-repo to replicate this one because it's _very weird_:

https://github.com/tmcw/mdast-uglify-bug

The jist is that `UglifyJS` causes mdast to fail on processing input that it would otherwise be able to process.

**Comment by tmcw** [comment]
Okay: narrowed it down that the `-c` option, not the `-m` option, triggers this.

**Comment by anko** [comment]
If code breaks when passed through UglifyJS, isn't that an UglifyJS bug?

Mdast [uses](https://github.com/wooorm/mdast/blob/master/package.json#L64) [esmangle](https://github.com/estools/esmangle) to minify.

Have I misunderstood?

**Comment by tmcw** [comment]
I've opened [an upstream bug in UglifyJS2](https://github.com/mishoo/UglifyJS2/issues/751)

**Comment by wooorm** [comment]
Weird! I found the culprit though, a fix is almost on its way. You’ll see what happened in the diff, and maybe uglify2 can do something with that (I believe it’s not a bug on my side, albeit some confusing code).
