### ISSUE TITLE
Paragraph `mdast.stringify` creates line-breaks on return

### ISSUE THREAD

**Issue by dthree** [wooorm/mdast#43]
When invoking `mdast.stringify` on a paragraph node and all of its child nodes, it renders the original paragraph with line breaks. Example:

```text
This is a markdown pargraph with a [link](http://this-page-intentionally-left-blank.org) to something silly.
```

On stringifying this, one gets:

```text
This is a markdown pargraph with a 
[link](http://this-page-intentionally-left-blank.org)
 to something silly.
```

**Comment by wooorm** [comment]
Thanks, clearly a bug :)

**Comment by dthree** [comment]
:)

I added a compensation in `wat` for now that accommodates this, but I'll get rid of it as soon as this bug is closed. Thanks!

**Comment by wooorm** [comment]
I just used this example:

```js
var mdast = require('.');
var fixture = 'This is a markdown pargraph with a [link](http://this-page-intentionally-left-blank.org) to something silly.';

var ast = mdast.parse(fixture);
var paragraph = ast.children[0];

console.log(mdast.stringify(paragraph));
```

Yields:

```text
This is a markdown pargraph with a [link](http://this-page-intentionally-left-blank.org) to something silly.
```

Meaning, I don’t see extra line-breaks!

What was your code like?

**Comment by dthree** [comment]
@wooorm I think @anko might have just nailed it. This had me so confused!

I'm using Sublime 2 on Windows, and this defaults to the wrong line endings, which probably created the problem. I usually fix this in linting, but I haven't linted again in a few days and I guess a file or two was missed.

Let me fix this up (and change my Sublime defaults), and I'll let you know if it fixed the problem. Thanks for the insight anko.

**Comment by wooorm** [comment]
Cool, do let me know! TBH I haven’t tested a lot with different line endings, there’s a little bit [here](https://github.com/wooorm/mdast/blob/4ae4d9a262803198b7c9dd7ac077a023557dee0f/lib/utilities.js#L146) but that’s all. But there’s no support for writing DOS line endings either.

**Comment by dthree** [comment]
Haha - there shouldn't be. :) No worries.

**Comment by wooorm** [comment]
P.S. @anko thanks a lot for figuring this out.

@dthree was this indeed the problem, and did removing those line-endings fix it?

**Comment by wooorm** [comment]
@dthree Any word on this? :smile:

**Comment by dthree** [comment]
@wooorm Sorry! Should be able to check this out today. I'll let you know.

**Comment by wooorm** [comment]
:+1:

**Comment by wooorm** [comment]
@wat Closing this, ping me if you ever find if that’s indeed it!

**Comment by dthree** [comment]
@wooorm Egad! Sorry about that. Yeah, I will. :)

BTW, `mdast` did miracles for me on `wat`. I should have a full working demo in about a week, if you're interested :)

**Comment by wooorm** [comment]
@dthree Cool! Yeah I’m interested :+1:

**Comment by dthree** [comment]
:+1:
