### ISSUE TITLE
Ways to use global mdast plugins with CLI?

### ISSUE THREAD

**Issue by eush77** [wooorm/mdast#46]
What is the preferred way of using globally installed plugins with CLI?

```
$ echo "# hello" | mdast -u mdast-html
# hello

<stdin>
        1:1  error    Error: Cannot find module 'mdast-html'
```

It just worked before. I found two ways of working around it.

- Including `$(npm root -g)` in `$NODE_PATH`:
```
$ echo "# hello" | env NODE_PATH="$(npm root -g):$NODE_PATH" mdast -u mdast-html
```

- Specifying full path to a plugin:
```
$ echo "# hello" | mdast -u "$(npm root -g)/mdast-html"
```

Both ways are somewhat clumsy. Is there a simpler way of doing that or some relevant configuration option?

**Comment by wooorm** [comment]
Are both mdast and mdast-html global in your example case? I agree that it should work, and it worked before, so this is indeed a bug.

**Comment by eush77** [comment]
> Are both mdast and mdast-html global in your example case?

Yes, they are.

**Comment by eush77** [comment]
Just noticed that in my case `mdast` was npmlinked. After removing the link and doing `npm i mdast -g` global plugins are working again.

Perhaps mdast should also consult npm prefix as a last step if none of other [patterns] match.

[patterns]: https://github.com/wooorm/mdast/blob/4ae4d9a262803198b7c9dd7ac077a023557dee0f/lib/cli/file-pipeline/configure.js#L67-L73

**Comment by wooorm** [comment]
Seems to not be very simple: <https://github.com/h2non/requireg#differences-with-require>

**Comment by wooorm** [comment]
Also: I don’t think many people will link mdast into global, so if for this to work 5+ paths need to be checked, I’d rather decline...

**Comment by eush77** [comment]
> if for this to work 5+ paths need to be checked, I’d rather decline

In reality, there are not so many of them.

From [Node docs](https://iojs.org/api/modules.html#modules_loading_from_the_global_folders):

> If the NODE_PATH environment variable is set to a colon-delimited list of absolute paths, then io.js will search those paths for modules if they are not found elsewhere.
> […]
>
> Additionally, io.js will search in the following locations:
> 1: $HOME/.node_modules
> 2: $HOME/.node_libraries
> 3: $PREFIX/lib/node
>
> Where $HOME is the user's home directory, and $PREFIX is io.js's configured node_prefix. 
>
> These are mostly for historic reasons.

Note that (1) these paths practically deprecated, (2) __none__ of them is where npm puts modules upon global install, and (3) they are part of the Node core, so default `require()` algorithm works just fine!

```
$ echo 'module.exports=function(){return function(ast){ast.children.push({"type":"text","value":"hi there"})}}' >~/.node_libraries/hello.js
$ echo '# hello' |mdast -u hello
# hello

hi there

<stdin>: no issues found
```

So this is not what this issue is about. It really is about paths used by npm but _not_ native to the Node. From [npm docs](https://docs.npmjs.com/files/folders#node-modules):

> Global installs on Unix systems go to {prefix}/lib/node_modules. Global installs on Windows go to {prefix}/node_modules (that is, no lib folder.)

And so there are only two paths currently missing: `{prefix}/lib/node_modules` and `{prefix}/node_modules`.

**Comment by wooorm** [comment]
That makes things better. Know if it's easy to access that prefix reliably, sync?

**Comment by eush77** [comment]
First of all, npmrc needs to be taken into account, you can use [`rc`](https://github.com/dominictarr/rc) for that.

[This one liner][npm-prefix] worked for me pretty well:
```js
rc('npm', null, []).prefix || path.resolve(process.execPath, '../..');
```

[npm-prefix]: https://github.com/eush77/npm-prefix/blob/dd6a85a980aace01dfee436932186e19f0e73610/index.js#L9

**Comment by wooorm** [comment]
Cool! Any reason why the windows case is not handled by your module?

**Comment by eush77** [comment]
It is handled in 1.0.1 :)

**Comment by wooorm** [comment]
One last Q: I'd like to only load global plug-ins when mdast is global too. That prevents a local mdast from loading a global plugin (by throwing a helpful error). Any idea if and how that would be possible? I have no clue, maybe you do, but this looks important.

**Comment by eush77** [comment]
One idea is to check if `process.argv[1]` is `{prefix}/bin/mdast` (`{prefix}/mdast` on Windows). That is not very pretty though.

Alternatively, if `__dirname` is under `{prefix}`, then mdast is definitely global (but in this case it could be not installed directly by the user, and this test fails if mdast is linked).

**Comment by wooorm** [comment]
I haven’t checked this on Windows. Are you able to test there?
I opted for checking if `process.argv[1]` is inside `$prefix`, which seemed like the simplest check for this.
I tested in npm-run scripts, and with using a linked mdast(1).
I think this should work :smile:

**Comment by eush77** [comment]
> I haven’t checked this on Windows. Are you able to test there?

Nope, sorry.

**Comment by wooorm** [comment]
Darn, well, I think this should work. So let’s leave it at that!

**Comment by eush77** [comment]
:+1:
