### ISSUE TITLE
Print warnings & errors to stderr?

### ISSUE THREAD

**Issue by eush77** [wooorm/mdast#47]
[One of the examples](https://github.com/wooorm/mdast/blob/master/lib/cli/cli.js#L200) in `mdast --help` is not working correctly:

```
$ cat readme.md
- 1
- 2
$ cat readme.md | mdast -s 'setext: true, bullet: "*"' > readme-new.md
$ cat readme-new.md
*   1
*   2

<stdin>: no issues found
```

**Comment by wooorm** [comment]
Hmm that is indeed wrong. However, I'm not sure what the best practice is for showing informational counts (such as these). Would that be stderr?

**Comment by wooorm** [comment]
Now, with this update, your example looks as follows:

```
🚀  mdast master [?]: cat ex.md 
- 1
- 2

🚀  mdast master [?]: cat ex.md | bin/mdast --no-rc -s 'setext: true, bullet: "*"' > new.md

<stdin>: no issues found

🚀  mdast master [?]: cat new.md 
*   1
*   2
```

**Comment by eush77** [comment]
:+1:
