### ISSUE TITLE
Watching files

### ISSUE THREAD

**Issue by chcokr** [wooorm/mdast#51]
Hi, thanks for your work. I'm trying to use `mdast-lint`, and am thinking it'd be wonderful to have something like a `--watch` option built into `mdast`.

**Comment by wooorm** [comment]
It’s certainly a goal. I think it can be useful. Currently, you can use `markdown-linter` for atom with live hinting, and `Schiba` which is a markdown previewer but also with mdast-lint.

**Comment by chcokr** [comment]
Thanks. Yeah, I don't want to need Atom or Schiba to do my linting...

Maybe I could help with a PR? My idea is that all plugins attached to the current session of `mdast` get executed every time the target file saves. How correct is this?

**Comment by wooorm** [comment]
Pretty correct :) You’ll probably want to watch (e.g., with mikael/watch), and intercept [here](https://github.com/wooorm/mdast/blob/eb0e8a7bf57a94085992786a2c7d9739503d7cc3/lib/cli/index.js#L35)

**Comment by anko** [comment]
Watch library tip: [mikeal/watch](https://github.com/mikeal/watch) wraps the old [`fs.watchFile`](https://nodejs.org/api/fs.html#fs_fs_watchfile_filename_options_listener), which inefficiently polls the filesystem. The newer [`fs.watch`](https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener) uses platform-specific notification systems when possible, and is usually better every way.

**Comment by wooorm** [comment]
Is it possible/easy to implement, to use [either fs.watch when available and fall back to fs.watchFile](https://nodejs.org/api/fs.html#fs_availability)?

**Comment by anko** [comment]
I searched a bit: looks like [bevry/watchr](https://github.com/bevry/watchr) does that.

**Comment by wooorm** [comment]
Nice!

**Comment by chcokr** [comment]
I took a look at what [babel](https://github.com/babel/babel) uses, and it looks like it uses [chokidar](https://github.com/paulmillr/chokidar), which seems well-prepared for production use. Can I go ahead with a PR?

**Comment by wooorm** [comment]
I have no experience with it, but judging the list of implementations, I’d say yes :)

**Comment by chcokr** [comment]
Awesome, I'll submit a PR within the next few days.

**Comment by chcokr** [comment]
So I started working on the PR. Quick Q: I found out that when you run `mdast` inside this repo, the `readme.md` gets rewritten. A naive implementation of `--watch` would cause an infinite loop because of this.

My question is: which part of the `.mdastrc` is causing this?

**Comment by chcokr** [comment]
Oh, it's `"output": true`, duh. I'll continue to work on the PR.

**Comment by wooorm** [comment]
:+1: good luck

**Comment by chcokr** [comment]
I think I'm close to being done, I need to figure out how to avoid the infinite loop caused by `"output": true`.

As far as I know, there are two ways to define this `"output"` property: via `.mdastrc` and via CLI's `--output` option. What is the best way to get a single final verdict for `"output"` that covers both possibilities?

**Comment by chcokr** [comment]
After hours of fighting race conditions pertaining to the "infinite loop" problem, I'm starting to question whether we should even allow the user to watch a file that `mdast` will rewrite over.

Because, think about it - wouldn't it be awkward to see your file change soon after you save it? The user should instead really be storing the post-rewrite content into a different file.

Instead of fighting the race conditions, I'm thinking it could be a better idea to just avoid them entirely.

Other than that, I think I'm pretty much done. @wooorm What do you think?

**Comment by wooorm** [comment]
I agree that files which would normally be regenerated, should not (initially) be output by the watch command.
However, mdast can also output to different directories and to non-markdown files, an example is mdast [compiling it’s docs to `man/`](https://github.com/wooorm/mdast/blob/master/.mdastrc-man).

We could [turn off writing to the file-system](https://github.com/wooorm/mdast/blob/eb0e8a7bf57a94085992786a2c7d9739503d7cc3/lib/cli/file-pipeline/file-system.js#L46), but that would prohibit the use of mdast to create files, like the aforementioned man pages.

Alternatively, we can check if the _content_ changed instead inside the watch: mdast generates the same output as the input document, when it created the input itself.

**Comment by chcokr** [comment]
Thanks. How about this: when a file being rewritten is also being watched, we give the following warning:
```
You're watching file blah.md, but mdast is configured to rewrite over the file.
To avoid race conditions, mdast will not rewrite over the file while you're watching,
but instead hold the output in memory. When you exit the watch with a SIGINT (CTRL+C),
then mdast will rewrite over the file with the latest output.
```
....and we do as the warning says.

I think this is a good compromise among everything. What do you think?

**Comment by wooorm** [comment]
I’m fine with that!

Also, could you create a pull-request / branch with your work? That means I can help you with writing this, reply with comments, steer you in the right directions, &c.

**Comment by chcokr** [comment]
Yeah of course - I was just preparing up for a PR. Coming soon

**Comment by wooorm** [comment]
:+1:

**Comment by chcokr** [comment]
Let's continue the discussion in #57.
