### ISSUE TITLE
Is there an "encode" method to insert escaped text into the AST?

### ISSUE THREAD

**Issue by retorquere** [wooorm/mdast#54]
I sometimes have to insert text-as-is into the AST, e.g. I need to insert `(Taylor, Stouffer, & Meehl, 2011)` in a way that this exact text turns up in the markdown rendered to HTML. For this I need to insert something like `\(Taylor, Stouffer, & Meehl, 2011\)`. Can mdast do this for me? Or should I use something like markdown-escape?

**Comment by wooorm** [comment]
No, it doesn’t. Maybe it should. However, there’s a difference between what GitHub, CommonMark, and others see as “escaped” (making it a parsing question). The stringification phase simply checks for `escape` nodes and prepends a slash before them.

There should be a [utility](https://github.com/wooorm/mdast/blob/master/doc/plugins.md#list-of-utilities) for this IMHO.

**Comment by retorquere** [comment]
Cool.
