### ISSUE TITLE
Do not output blank lines between definitions

### ISSUE THREAD

**Issue by retorquere** [wooorm/mdast#55]
Source and reprocessed versions at https://gist.github.com/anonymous/3bf6b6095f73702c187d

**Comment by wooorm** [comment]
Yup, it does. mdast inserts new-lines between definitions, like it does between other block-nodes. What’s the question?

**Comment by retorquere** [comment]
Ok, can I have it not do that? :) I would prefer the markdown to round-trip
cleanly.

**Comment by wooorm** [comment]
We could have a [setting](https://github.com/wooorm/mdast/blob/master/doc/mdastsetting.7.md) for that.

mdast cannot “round trip cleanly”, because it doesn’t [store everything](https://github.com/wooorm/mdast/issues/32) inside the syntax tree.

**Comment by retorquere** [comment]
I've read #30 and I agree.

**Comment by wooorm** [comment]
:+1: Can I close this? Or do you want an option for this?

**Comment by retorquere** [comment]
This can be closed. I think I can explain to my users why this behavior is,
on the whole, desirable.

**Comment by wooorm** [comment]
:+1:
