### ISSUE TITLE
Watch: Process just the files being affected

### ISSUE THREAD

**Issue by chcokr** [wooorm/mdast#60]
Spin-off from #57.

**Comment by wooorm** [comment]
Are you interested in tackling this? I can of course also tackle this but it seems like you’re getting the hang of mdast 😄

I just checked, and you’ll probably want to only run the [`transform` and `log`](https://github.com/wooorm/mdast/blob/1dbcf4fb456bfbe3d5cf987f1c7ee58f1f456f7d/lib/cli/file-set-pipeline/index.js#L30-L31) middleware of the filepipeline (called [here](https://github.com/wooorm/mdast/blob/1dbcf4fb456bfbe3d5cf987f1c7ee58f1f456f7d/lib/cli/index.js#L30), defined [here](https://github.com/wooorm/mdast/blob/1dbcf4fb456bfbe3d5cf987f1c7ee58f1f456f7d/lib/cli/file-set-pipeline/index.js#L26).

We could also make sure the other tasks, [`configure`, `traverse`, and `stdin`](https://github.com/wooorm/mdast/blob/1dbcf4fb456bfbe3d5cf987f1c7ee58f1f456f7d/lib/cli/file-set-pipeline/index.js#L27-L29) are not run the they are already invoked with the same [`CLI`](https://github.com/wooorm/mdast/blob/1dbcf4fb456bfbe3d5cf987f1c7ee58f1f456f7d/lib/cli/index.js#L30) object.

**Comment by chcokr** [comment]
I am indeed interested! I think I can come up with a PR within a week or so.

**Comment by wooorm** [comment]
Great to hear! :+1:

**Comment by wooorm** [comment]
@chcokr Friendly ping! :smile:

**Comment by chcokr** [comment]
Thanks @wooorm. Yeah I should really get to it, just have been really busy this week. Let's see what I can get done this weekend.

**Comment by wooorm** [comment]
:+1:

**Comment by chcokr** [comment]
Hey, so would running `file-pipeline` (not `file-set-pipelin`) on just the modified file work?

**Comment by wooorm** [comment]
I’d suggest still using a file-set, just because more than one file is processed and using a set should make that easy!

**Comment by chcokr** [comment]
Gotcha. I decided to go with the second approach you suggested:

```
We could also make sure the other tasks, configure, traverse, and stdin are not run the they are already invoked with the same CLI object.
```

I'm working on this approach. I noticed something weird - if I don't run `traverse` during watch, prior warnings pile up. Any idea why?

**Comment by chcokr** [comment]
Other than that, I think I'm actually almost done.

**Comment by wooorm** [comment]
I’m not sure what you’re referring to, what kind of errors are piling up?

**Comment by chcokr** [comment]
Let me open up my PR and we can debug together. PR coming soon.

**Comment by wooorm** [comment]
:+1:

**Comment by chcokr** [comment]
Discussion continues in #85.
