### ISSUE TITLE
ANSI document highlighting

### ISSUE THREAD

**Issue by maboiteaspam** [wooorm/mdast#68]
Hi !

I wonders hardly if you believe it s possible to use that lib to output formatted markdown on cli.

I did myself wrote some modules for that, but found it really difficult, the final results is not as good as i would like.
Let s say for the basics it s just ok and i d like get something much better.

So here am i looking for some ideas, advises or whatever.

Thanks !

**Comment by wooorm** [comment]
@maboiteaspam Thanks for reporting your Issue;

I’m not sure what you’re asking, are you asking for the [`--output`](https://github.com/wooorm/mdast/blob/master/doc/mdast.1.md#-o---output-path) option?

> Let s say for the basics it s just ok and i d like get something much better.

Could you show some examples of what input should generate what output?

**Comment by maboiteaspam** [comment]
Hi !

It s not issue. Just questions about display formatted markdown on CLI.

I don t think its about --output, as this switch its to control where the data are piped out.

I do want to display pretty printed markdown in my command line.

I achieve it once (see below), but i m not satisfied. Especially the MD parsing step. So i m looking for an alternative.

I m sorry, i never produced a gif or whatever of the modules i made to do that,
The most straightforward example would be the screenshot available here
https://github.com/RodrigoEspinosa/md-open
It is where i started myself : )

Then after i made more work, to display more advanced syntax. 
but you ll need to try them or wait i produce a gif or something.
https://github.com/maboiteaspam/showusage
https://github.com/maboiteaspam/md-stream-utils
https://github.com/maboiteaspam/md-tokenizer

Hope its more clear !

**Comment by eush77** [comment]
So you need something like [marked-terminal](https://github.com/mikaelbr/marked-terminal) but for mdast?

**Comment by wooorm** [comment]
@eush77 Thanks!

@maboiteaspam Do you want syntax highlighting, or document viewing? As in, `*foo*` should be displayed in italics, but should it still have the asterisks?

**Comment by maboiteaspam** [comment]
rocks, it s great !
