### ISSUE TITLE
Option to set maximum number of consecutive empty lines

### ISSUE THREAD

**Issue by tkruse** [wooorm/mdast#77]
Hi,

I did not see such an option, but it might be useful to separate larger chapters with more than one blank line.
Is there such a feature?

**Comment by wooorm** [comment]
Interesting! How would this work?

Would you like an option to have more than one newline before headings of a certain depth (e.g., `h1`)?

Could this option also be useful for non-heading nodes? E.g., having more spacing before (and/or after?) a horizontal rule?

**Comment by tkruse** [comment]
Ah, actually, I am now much less passionate about it after I slept over it. Probably best to stick with a single line.

What I though was that if an author leaves n consecutive blank lines anywhere in the document, and sets maximum blank lines to something bigger than 1, then mdast merely reduces to that number.

I don't think mdast should add newlines, that just makes everything more complicated to configure, for too little benefit.

**Comment by wooorm** [comment]
I think I agree, I do know that some people do it though, but I’m not sure if it can be easily configured!

**Comment by tkruse** [comment]
Hi,

So I did get interested in mdast for this project: https://github.com/isocpp/CppCoreGuidelines/pull/219

It seems there is some interest for this feature. What I imagine is a config entry lke this:
```
{"settings": 
  {"max_consecutive_empty_lines": 3}
}
```

that with this input:

```
## header1

## header2



## header3







## header4
```

will yield:

```
## header1

## header2



## header3



## header4
```

So only consecutive empty lines that exceed the given maximum would be shortened to that maximum (Except where markdown requires more than one empty line). No single empty lines would get expanded to more. I believe this should be easy to configure and understand.

The other possibility would be to just switch off mdast checking/fixing of multiple empty lines. Note that mdast-lint already allows some configuration with ```no-consecutive-blank-lines```
https://github.com/wooorm/mdast-lint/blob/master/doc/rules.md#no-consecutive-blank-lines

**Comment by wooorm** [comment]
Remember the amount of empty lines might be achievable, due to positions, but this information is otherwise not available in the AST, and I don't feel the AST should be treated like a CST in such a way.

Put it more bluntly, this setting would differ from all others in the way that this setting looks at the input markdown, whereas all other settings just look at the nodes in the syntax tree.

I'm not really opposed to a setting for these empty lines, but I'd rather have something that adds two lines before a h1 versus this proposal

**Comment by tkruse** [comment]
Ah, so mdast basically just creates an AST and then renders it in markdown? I see the problem. In that case you can reclose, and maybe just using mdast-lint will be fine.

**Comment by wooorm** [comment]
Yup! That has its good parts, namely minimalistic and compatible output, and ensures markdown can easily be generated on the fly from other formats (e.g., by a program or by from another language such as html). And the downside is that it can't compile back precisely to the input.
