### ISSUE TITLE
AST specification?

### ISSUE THREAD

**Issue by tmcw** [wooorm/mdast#79]
I'm considering swapping out the template-based markdown generation in [documentation](https://github.com/documentationjs/documentation) for generating an mdast-compatible representation and then stringifying with this module.

I think the approach has potential, but getting started I'm not sure where to learn about what inputs to `stringify()` will work: I can parse and debug the current output I get, but is there a document or a file I should be reading to get up to speed on what mdast nodes exist and what they're called? Thanks!

**Comment by eush77** [comment]
Have you seen [this document][mdastnode]?

[mdastnode]: https://github.com/wooorm/mdast/blob/master/doc/mdastnode.7.md

**Comment by wooorm** [comment]
@tmcw did @eush77's link help, or were you searching for something else?

**Comment by tmcw** [comment]
Ah! Perfect, I had checked the other docs in docs/ but not that one - I think the morning brain thought node = nodejs rather than ast node :)

**Comment by wooorm** [comment]
Ah, yeah that can probably be confusing in the morning :wink: 

I think this can be closed right?

P.S. Cool to see interest in going for mast, ping if you need help!
