### ISSUE TITLE
Using mdast to transform non-markdown content

### ISSUE THREAD

**Issue by anandthakker** [wooorm/mdast#81]
Over at https://github.com/documentationjs/documentation/pull/150, we've got a use case for mdast consuming non-markdown data (json, basically), and then producing markdown from them.  On the one hand, it seems like it would be nice to have this happen in a plugin, so that it could be composed with other plugins.  On the other hand, mdast's parsing system seems to be tuned to consume markdown and variants thereof.

 @wooorm do you have thoughts on this?

**Comment by wooorm** [comment]
Sure, switching the `Parser` is very much supported. However, some plugins (like mdast-yaml) expect the default parser, so you might run into some problems there!

Other than that, a `Parser` (settable on an `mdast` instance by an [attacher](https://github.com/wooorm/mdast/blob/master/doc/mdastplugin.3.md#function-attachermdast-options-fileset)) **must** be a constructor, which when instantiated exposes a `parse` method. The constructor accepts a [`VFile`](https://github.com/wooorm/vfile) and settings (given to `mdast.parse`, `mdast.process`). Later, the `parse` method must parse this file into an [mdastnode(7)](https://github.com/wooorm/mdast/blob/master/doc/mdastnode.7.md), which will be given to the [“transformer”](https://github.com/wooorm/mdast/blob/master/doc/mdastplugin.3.md#function-transformernode-file-next)s.

Hope this short intro helps. Can I close this?

**Comment by anandthakker** [comment]
Thanks, this helps!  Closing here.

**Comment by wooorm** [comment]
:+1:
