### ISSUE TITLE
Version in distribution files

### ISSUE THREAD

**Issue by digitalmoksha** [wooorm/mdast#86]
Just as a small suggestion, would it be possible to have a one line comment at the beginning of the minified file, that indicates the current version of the file?  It makes it much easier to maintain and upgrade later (rather than having to add the version to the filename).  I see this with many other js files, and it's very helpful.

**Comment by wooorm** [comment]
Sure that’s possible. The downside of this is that I’d have to change the version-number every time I publish. In fact, I recommend using a [package manager](https://github.com/wooorm/mdast/blob/master/doc/getting-started.md#package-managers) when using **mdast**, which already has the version pinned down.

Could you let me know if you’d still like this (in which case, I’ll add it), or if using a package manager is a feasible alternative?

**Comment by digitalmoksha** [comment]
There are cases where a package manager is not so practical, for example I'm embedding this in an OS X app.  Or if I use in a Rails app - I know there are ways to integrate bower with it, but haven't researched that completely yet.

I don't want to create extra work for you, so don't do it if you need to do it manually.  If you're automating your build, one way to do it is how `markdown-it` does it: (from the Makefile)

```
browserify:
	rm -rf ./dist
	mkdir dist
	# Browserify
	( printf "/*! ${NPM_PACKAGE} ${NPM_VERSION} ${GITHUB_PROJ} @license MIT */" ; \
		browserify ./ -s markdownit \
		) > dist/markdown-it.js
	# Minify
	uglifyjs dist/markdown-it.js -b beautify=false,ascii-only=true -c -m \
		--preamble "/*! ${NPM_PACKAGE} ${NPM_VERSION} ${GITHUB_PROJ} @license MIT */" \
		> dist/markdown-it.min.js
```

**Comment by wooorm** [comment]
Okay I’ll investigate :) Maybe there should be an mdast for JS, with a plug-in to do this haha :wink:

**Comment by digitalmoksha** [comment]
Sweet!  Thanks...
