### ISSUE TITLE
Missing `blockText` block method in parser...

### ISSUE THREAD

**Issue by digitalmoksha** [wooorm/mdast#87]
Not sure if this is an issue or not.  While doing some debugging, I noticed that `blockText` is an entry in the `Parser.prototype.blockMethods` array.  However, there is no corresponding entry in  `Parser.prototype.blockTokenizers`.  If the parser ever does come to the `blockText` method (which is last), an exception will end up getting thrown.  Not sure if in general it would ever get that far.

Just bringing to your attention...

**Comment by wooorm** [comment]
Thanks, totally missed that: probably originated a long time ago, but it couldn’t do any harm as it should (?) be impossible to reach after `paragraph`!
