### ISSUE TITLE
mdast writes an empty line before EOF

### ISSUE THREAD

**Issue by sils1297** [wooorm/mdast#91]
Apparently when I generate a file using mdast, it has *two* `\n`s before EOF, one would be better :)

**Comment by wooorm** [comment]
When piping or when using `-o`?

**Comment by sils1297** [comment]
I'm piping, using it via a Bear in coala.

**Comment by sils1297** [comment]
Shouldn't make a difference should it?

**Comment by sils1297** [comment]
(Note that we capture stderr in an extra stream so it's only the stdout output)

**Comment by wooorm** [comment]
It does, because I opted both to behave differently. For example, all information and warnings are passed to stderr(4)).

When a user is writing to a TTY, I prefer an extra newline for things to look better, but as mentioned before that should’ve been stderr(4). I’ll investigate.
