### ISSUE TITLE
Add nvm installation instructions

### ISSUE THREAD

**Issue by sils1297** [wooorm/mdast#92]
Would be nice to point out how to install the newest nodejs in the readme/docs. It's like a two command thing so it shouldn't bloat your docs.

**Comment by wooorm** [comment]
The getting started docs already mention how to [download node](https://github.com/wooorm/mdast/blob/master/doc/getting-started.md#package-managers) (which points to the latest version).

I don’t mind referencing nvm, but I’d like it to be short. What link would you suggest?

**Comment by sils1297** [comment]
No link, I'd just put:

    ```
    curl https://raw.githubusercontent.com/creationix/nvm/v0.16.1/install.sh | sh && source ~/.bashrc && nvm install 5.1.0
    ```

or so there, you're the expert on that :)

**Comment by wooorm** [comment]
Hmm, I appreciate the code but I’d rather not keep updating the guide for each nvm and node version. On point, the nvm version you references is out of date. I think the middleground here would be to link to nvm’s installation guide (<https://github.com/creationix/nvm#install-script>) and its usage docs (<https://github.com/creationix/nvm#usage>).

Thoughts?
