### ISSUE TITLE
problems with check for PLUGIN_KEY in merge in lib/cli/configuration.js

### ISSUE THREAD

**Issue by iamstarkov** [wooorm/mdast#99]
so basically if mdast plugin also has `plugins=["foo", "bar"]` option, then [`merge` function][merge] and [check for `PLUGIN_KEY=plugins`][check] will turn them to `plugins={ foo: null, bar: null }`

*.mdastrc:*
```json
{
	"plugins": {
		"mdast-demo": {
			"plugins": [ "foo", "bar" ], 
			"plugins2": [ "foo", "bar" ]
		}
	}
}
```
*mdast-demo:*
```js
module.exports = function attacher(processor, options) {
  return function transformer(ast) {
    console.log('plugins', options.plugins);
    console.log('plugins2', options.plugins2);
  };
};
```

*log:*

    plugins { foo: null, bar: null }
    plugins2 [ 'foo', 'bar' ]

[merge]: https://github.com/wooorm/mdast/blob/master/lib/cli/configuration.js#L69
[check]: https://github.com/wooorm/mdast/blob/master/lib/cli/configuration.js#L81

**Comment by iamstarkov** [comment]
I found this bug while was debugging [mdast-textr](https://github.com/denysdovhan/mdast-textr)

**Comment by iamstarkov** [comment]
I tried to fix it on my own, but merge is too complicated for me, sorry(

**Comment by wooorm** [comment]
Thanks for raising the issue, @iamstarkov!

**Comment by iamstarkov** [comment]
no problem =)
